import 'reflect-metadata';
import { PrimaryGeneratedColumn, CreateDateColumn, UpdateDateColumn } from 'typeorm';

/**
 * Abstract base entity class for all Connect 2.0 database entities.
 * Provides common fields: UUID primary key, created_at, and updated_at timestamps.
 *
 * All entity classes should extend this base class to ensure consistent
 * entity structure across the application.
 *
 * Example usage:
 * ```typescript
 * import { Entity, Column } from 'typeorm';
 * import { BaseEntity } from './BaseEntity';
 *
 * @Entity('users')
 * export class User extends BaseEntity {
 *   @Column()
 *   email: string;
 *
 *   @Column()
 *   name: string;
 * }
 * ```
 */
export abstract class BaseEntity {
  /**
   * Unique identifier for the entity (UUID v4).
   * Automatically generated by PostgreSQL using gen_random_uuid().
   * Readonly after creation - cannot be modified.
   */
  @PrimaryGeneratedColumn('uuid')
  readonly id!: string;

  /**
   * Timestamp when the entity was created.
   * Automatically set by TypeORM on insert.
   * Readonly after creation - cannot be modified.
   */
  @CreateDateColumn({ name: 'created_at' })
  readonly created_at!: Date;

  /**
   * Timestamp when the entity was last updated.
   * Automatically updated by TypeORM on every update.
   * Readonly in application code - TypeORM updates this automatically.
   */
  @UpdateDateColumn({ name: 'updated_at' })
  readonly updated_at!: Date;
}
